# French translations for Open-Capture For Invoices
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2021-11-04 16:14+0100\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: fr\n"
"Language-Team: fr <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.9.1\n"

#: src/backend/classes/MaarchWebServices.py:39
msgid "HOST_NOT_FOUND"
msgstr "L'URL de l'hôte n'existe pas"

#: src/backend/controllers/accounts.py:43 src/backend/models/accounts.py:51
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte fournisseur"

#: src/backend/controllers/accounts.py:56 src/backend/models/accounts.py:70
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'adresse"

#: src/backend/controllers/accounts.py:76
#: src/backend/controllers/accounts.py:82
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la mise à jour du fournisseur"

#: src/backend/controllers/accounts.py:108
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions du compte fournisseur"

#: src/backend/controllers/accounts.py:133
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages du compte fournisseur"

#: src/backend/controllers/accounts.py:159
#: src/backend/controllers/accounts.py:165
#: src/backend/controllers/accounts.py:191
#: src/backend/controllers/accounts.py:197 src/backend/models/accounts.py:108
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Erreur lors de la mise à jour de l'adresse"

#: src/backend/controllers/accounts.py:224 src/backend/models/accounts.py:124
msgid "CREATE_ADDRESS_ERROR"
msgstr "Erreur lors de la création de l'adresse"

#: src/backend/controllers/accounts.py:258
#: src/backend/controllers/accounts.py:264 src/backend/models/accounts.py:140
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la création du compte fournisseur"

#: src/backend/controllers/accounts.py:265
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte fournisseur existe déjà avec ce numéro de TVA"

#: src/backend/controllers/accounts.py:288 src/backend/controllers/user.py:86
#: src/backend/models/accounts.py:192 src/backend/models/accounts.py:211
#: src/backend/models/accounts.py:226 src/backend/models/user.py:132
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte client"

#: src/backend/controllers/accounts.py:331
#: src/backend/controllers/accounts.py:337 src/backend/models/accounts.py:244
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la mise à jour du compte client"

#: src/backend/controllers/accounts.py:368
#: src/backend/controllers/accounts.py:374 src/backend/models/accounts.py:260
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la création du compte client"

#: src/backend/controllers/accounts.py:375
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte client existe déjà avec ce numéro de TVA"

#: src/backend/controllers/accounts.py:391
#: src/backend/controllers/accounts.py:397 src/backend/models/accounts.py:278
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Erreur lors de la suppression du compte client"

#: src/backend/controllers/accounts.py:414
#: src/backend/controllers/accounts.py:420 src/backend/models/accounts.py:158
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Erreur lors de la suppression du compte fournisseur"

#: src/backend/controllers/auth.py:80
msgid "LOGIN_ERROR"
msgstr "Erreur lors de la connexion"

#: src/backend/controllers/auth.py:95 src/backend/controllers/auth.py:103
#: src/backend/controllers/auth.py:105
msgid "JWT_ERROR"
msgstr "Erreur lors de l'authentification par token"

#: src/backend/controllers/config.py:46
msgid "CHANGE_LOCALE_ERROR"
msgstr "Erreur lors du changement de langue"

#: src/backend/controllers/forms.py:66 src/backend/controllers/forms.py:115
#: src/backend/models/forms.py:52
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du formulaire"

#: src/backend/controllers/forms.py:98
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Erreur lors de la récupération des champs du formulaire"

#: src/backend/controllers/forms.py:162 src/backend/controllers/forms.py:168
msgid "DELETE_FORM_ERROR"
msgstr "Erreur lors de la suppression du formulaire"

#: src/backend/controllers/forms.py:184
#: src/backend/controllers/positions_masks.py:154
msgid "COPY_OF"
msgstr "Copie de"

#: src/backend/controllers/forms.py:200 src/backend/controllers/forms.py:206
msgid "DUPLICATE_FORM_ERROR"
msgstr "Erreur lors de la duplication du formulaire"

#: src/backend/controllers/forms.py:223 src/backend/controllers/forms.py:229
msgid "DISABLE_FORM_ERROR"
msgstr "Erreur lors de la désactivation du formulaire"

#: src/backend/controllers/forms.py:246 src/backend/controllers/forms.py:252
msgid "ENABLE_FORM_ERROR"
msgstr "Erreur lors de l'activation du formulaire"

#: src/backend/controllers/forms.py:285 src/backend/controllers/forms.py:291
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr "Erreur lors de l'ajout dans l'historique"

#: src/backend/controllers/inputs.py:52 src/backend/controllers/inputs.py:58
msgid "UPDATE_INPUT_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne entrante"

#: src/backend/controllers/inputs.py:86
msgid "CREATE_INPUT_ERROR"
msgstr "Erreur lors de la création de la chaîne entrante"

#: src/backend/controllers/inputs.py:99
msgid "GET_INPUT_BY_ID_ERROR"
msgstr "Erreur lors de récupération de la chaîne entrante"

#: src/backend/controllers/inputs.py:123 src/backend/controllers/inputs.py:129
msgid "DELETE_INPUT_ERROR"
msgstr "Erreur lors de le suppression de la chaîne entrante"

#: src/backend/controllers/inputs.py:217
msgid "INCRON_CREATION_ERROR"
msgstr "Erreur lors de la création de l'incron"

#: src/backend/controllers/inputs.py:223
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Le script d'exemple n'existe pas"

#: src/backend/controllers/inputs.py:229
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier des scripts n'existe pas"

#: src/backend/controllers/outputs.py:71 src/backend/controllers/outputs.py:77
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Erreur lors de mise à jour de la chaîne sortante"

#: src/backend/controllers/outputs.py:102
msgid "CREATE_OUTPUT_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/controllers/outputs.py:115
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de la chaîne sortante"

#: src/backend/controllers/outputs.py:128
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération des types de chaîne sortante"

#: src/backend/controllers/outputs.py:145
#: src/backend/controllers/outputs.py:151
msgid "DELETE_OUTPUT_ERROR"
msgstr "Erreur lors de la suppression de la chaîne sortante"

#: src/backend/controllers/positions_masks.py:75
#: src/backend/controllers/positions_masks.py:92
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/controllers/positions_masks.py:137
#: src/backend/controllers/positions_masks.py:143
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Erreur lors de la suppression du masque de positionnement"

#: src/backend/controllers/positions_masks.py:170
#: src/backend/controllers/positions_masks.py:176
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la duplication du masque de positionnement"

#: src/backend/controllers/positions_masks.py:193
#: src/backend/controllers/positions_masks.py:199
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de désactivation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:216
#: src/backend/controllers/positions_masks.py:222
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de l'activation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:247
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:272
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des pages du masque de positionnement"

#: src/backend/controllers/positions_masks.py:292
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:312
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des pages du masque de positionnement"

#: src/backend/controllers/privileges.py:36
#: src/backend/controllers/privileges.py:64
msgid "GET_PRIVILEGES_ERROR"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/controllers/roles.py:53 src/backend/controllers/roles.py:59
#: src/backend/controllers/roles.py:106 src/backend/controllers/roles.py:112
#: src/backend/models/roles.py:70
msgid "UPDATE_ROLE_ERROR"
msgstr "Erreur lors de la mise à jour du rôle"

#: src/backend/controllers/roles.py:84 src/backend/models/roles.py:86
msgid "CREATE_ROLE_ERROR"
msgstr "Erreur lors de la création du rôle"

#: src/backend/controllers/roles.py:125
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du rôle"

#: src/backend/controllers/roles.py:142 src/backend/controllers/roles.py:148
msgid "DELETE_ROLE_ERROR"
msgstr "Erreur lors de la suppression du rôle"

#: src/backend/controllers/roles.py:165 src/backend/controllers/roles.py:171
msgid "DISABLE_ROLE_ERROR"
msgstr "Erreur lors de la désactivation du rôle"

#: src/backend/controllers/roles.py:188 src/backend/controllers/roles.py:194
msgid "ENABLE_ROLE_ERROR"
msgstr "Erreur lors de l'activation du rôle"

#: src/backend/controllers/splitter.py:61
#: src/backend/controllers/verifier.py:73
msgid "AT"
msgstr "à"

#: src/backend/controllers/status.py:35
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Erreur lors de la récupération des status"

#: src/backend/controllers/user.py:31
msgid "CREATE_USER_ERROR"
msgstr "Erreur lors de la création de l'utilisateur"

#: src/backend/controllers/user.py:69 src/backend/models/user.py:113
msgid "GET_USER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'utilisateur"

#: src/backend/controllers/user.py:100
msgid "UPDATE_PROFILE"
msgstr "Mise à jour du profile"

#: src/backend/controllers/user.py:101
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "L'ancien mot de passe ne corresponds pas"

#: src/backend/controllers/user.py:124 src/backend/controllers/user.py:130
#: src/backend/models/user.py:151
msgid "UPDATE_USER_ERROR"
msgstr "Erreur lors de la mise à jour de l'utilisateur"

#: src/backend/controllers/user.py:147 src/backend/controllers/user.py:153
msgid "DELETE_USER_ERROR"
msgstr "Erreur lors de la suppression de l'utilisateur"

#: src/backend/controllers/user.py:170 src/backend/controllers/user.py:176
msgid "DISABLE_USER_ERROR"
msgstr "Erreur lors de désactiver de l'utilisateur"

#: src/backend/controllers/user.py:193 src/backend/controllers/user.py:199
msgid "ENABLE_USER_ERROR"
msgstr "Erreur lors de l'activation de l'utilisateur"

#: src/backend/controllers/user.py:219 src/backend/controllers/user.py:225
#: src/backend/models/user.py:169
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Erreur lors de la mise à jour des comptes clients de l'utilisateur"

#: src/backend/controllers/verifier.py:56 src/backend/models/verifier.py:34
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de la facture"

#: src/backend/controllers/verifier.py:159
#: src/backend/controllers/verifier.py:249
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions de la facture"

#: src/backend/controllers/verifier.py:184
#: src/backend/controllers/verifier.py:269
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages de la facture"

#: src/backend/controllers/verifier.py:208
#: src/backend/controllers/verifier.py:228
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr "Erreur lors de la mise à jour des données de la facture"

#: src/backend/controllers/verifier.py:286
#: src/backend/controllers/verifier.py:292
msgid "DELETE_INVOICE_ERROR"
msgstr "Erreur lors de la suppression de la facture"

#: src/backend/controllers/verifier.py:310
#: src/backend/controllers/verifier.py:316
msgid "UPDATE_INVOICE_ERROR"
msgstr "Erreur lors de la mise à jour de la facture"

#: src/backend/controllers/verifier.py:336
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Erreur lors de la suppression du verrou sur la facture"

#: src/backend/controllers/verifier.py:435
#: src/backend/controllers/verifier.py:441
#: src/backend/controllers/verifier.py:447
msgid "EXPORT_MAARCH_ERROR"
msgstr "Erreur lors de l'export vers Maarch"

#: src/backend/controllers/verifier.py:442
msgid "PDF_FILE_NOT_FOUND"
msgstr "Le fichier PDF est introuvable"

#: src/backend/controllers/verifier.py:453
msgid "MAARCH_WS_INFO_WRONG"
msgstr "Les informations de connexion à Maarch sont erronnées"

#: src/backend/controllers/verifier.py:459
msgid "MAARCH_WS_INFO_EMPTY"
msgstr "Les informations de connexion à Maarch sont vides"

#: src/backend/controllers/verifier.py:545
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier de destination XML n'existe pas"

#: src/backend/controllers/verifier.py:551
msgid "EXPORT_XML_ERROR"
msgstr "Erreur lors de l'export XML"

#: src/backend/controllers/verifier.py:615
#: src/backend/controllers/verifier.py:618
#: src/backend/controllers/verifier.py:631
#: src/backend/controllers/verifier.py:648
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Erreur lors de la connexion à l'api de l'INSEE"

#: src/backend/controllers/verifier.py:670
msgid "VAT_NOT_VALID"
msgstr "Numéro de TVA invalide"

#: src/backend/controllers/verifier.py:674
msgid "VAT_API_ERROR"
msgstr "Impossible de joindre l'API de vérification du numéro de TVA"

#: src/backend/models/accounts.py:90
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour du fournisseur"

#: src/backend/models/auth.py:35 src/backend/models/user.py:37
msgid "BAD_USERNAME"
msgstr "Mauvais nom de compte"

#: src/backend/models/auth.py:37 src/backend/models/user.py:39
msgid "BAD_PASSWORD"
msgstr "Mauvais mot de passe"

#: src/backend/models/auth.py:39
msgid "USER_DELETED"
msgstr "Utilisateur supprimé"

#: src/backend/models/auth.py:41
msgid "USER_DISABLED"
msgstr "Utilisateur desactivé"

#: src/backend/models/custom_fields.py:45
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Erreur lors de la création du champ custom"

#: src/backend/models/custom_fields.py:48
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Le champ custom existe déjà"

#: src/backend/models/custom_fields.py:86
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour du champ custom"

#: src/backend/models/forms.py:71
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Erreur lors de la récupération du formulaire par défaut"

#: src/backend/models/forms.py:91
msgid "UPDATE_FORM_ERROR"
msgstr "Erreur lors de la mise à jour du formulaire"

#: src/backend/models/forms.py:109
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/models/forms.py:149
msgid "ADD_FORM_ERROR"
msgstr "Erreur lors de la création du formulaire"

#: src/backend/models/forms.py:152
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Le libellé de formulaire existe déjà"

#: src/backend/models/inputs.py:50
msgid "INPUT_DOESNT_EXISTS"
msgstr "La chaîne entrante n'existe pas"

#: src/backend/models/inputs.py:84
msgid "INPUT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne entrante"

#: src/backend/models/inputs.py:100
msgid "INPUT_CREATE_ERROR"
msgstr "Erreur lors de la création de la chaîne entrante"

#: src/backend/models/outputs.py:64
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "La chaîne sortante n'existe pas"

#: src/backend/models/outputs.py:83
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Le type de chaîne sortante n'existe aps"

#: src/backend/models/outputs.py:103
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne sortante"

#: src/backend/models/outputs.py:119
msgid "OUTPUT_CREATE_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/models/positions_masks.py:52
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/models/positions_masks.py:72
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la mise à jour du masque de positionnement"

#: src/backend/models/positions_masks.py:90
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du masque de positionnement"

#: src/backend/models/positions_masks.py:120
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la création du masque de positionnement"

#: src/backend/models/positions_masks.py:123
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Le libellé du masque de positionnement existe déjà"

#: src/backend/models/privileges.py:32 src/backend/models/privileges.py:49
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/models/roles.py:50
msgid "ROLE_DOESNT_EXISTS"
msgstr "Le rôle n'existe pas"

#: src/backend/models/roles.py:104
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour des privilèges du rôle"

#: src/backend/models/roles.py:122
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Erreur lors de la création des privilèges du rôle"

#: src/backend/models/status.py:32
msgid "NO_STATUS"
msgstr "Aucun status existant"

#: src/backend/models/user.py:41
msgid "USER"
msgstr "L'utilisateur"

#: src/backend/models/user.py:41
msgid "ALREADY_REGISTERED"
msgstr "est déjà enregistré"

#: src/backend/models/verifier.py:86 src/backend/models/verifier.py:103
msgid "INVOICE_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la facture"

#: src/backend/rest/splitter.py:39 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr "Erreur inconnue"

