# French translations for Open-Capture For Invoices
# Copyright (C) 2019 ORGANIZATION
# This file is distributed under the same license as the project
# FIRST AUTHOR <nathan.cheval@edissyum.com>, 2021.
msgid ""
msgstr ""
"Project-Id-Version:  0.1\n"
"Report-Msgid-Bugs-To: nathan.cheval@edissyum.com\n"
"POT-Creation-Date: 2022-05-17 10:28+0200\n"
"PO-Revision-Date: 2019-09-02 17:48+0200\n"
"Last-Translator: Nathan CHEVAL <nathan.cheval@edissyum.com>\n"
"Language: fr\n"
"Language-Team: fr <nathan.cheval@edissyum.com>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.9.1\n"

#: src/backend/classes/MaarchWebServices.py:39
msgid "HOST_NOT_FOUND"
msgstr "L'URL de l'hôte n'existe pas"

#: src/backend/controllers/accounts.py:47 src/backend/models/accounts.py:51
msgid "GET_SUPPLIER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte fournisseur"

#: src/backend/controllers/accounts.py:60 src/backend/models/accounts.py:70
msgid "GET_ADDRESS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'adresse"

#: src/backend/controllers/accounts.py:80
#: src/backend/controllers/accounts.py:86
msgid "UPDATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la mise à jour du fournisseur"

#: src/backend/controllers/accounts.py:112
msgid "UPDATE_SUPPLIER_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions du compte fournisseur"

#: src/backend/controllers/accounts.py:137
msgid "UPDATE_SUPPLIER_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages du compte fournisseur"

#: src/backend/controllers/accounts.py:163
#: src/backend/controllers/accounts.py:169
#: src/backend/controllers/accounts.py:195
#: src/backend/controllers/accounts.py:201 src/backend/models/accounts.py:108
msgid "UPDATE_ADDRESS_ERROR"
msgstr "Erreur lors de la mise à jour de l'adresse"

#: src/backend/controllers/accounts.py:228 src/backend/models/accounts.py:124
msgid "CREATE_ADDRESS_ERROR"
msgstr "Erreur lors de la création de l'adresse"

#: src/backend/controllers/accounts.py:262
#: src/backend/controllers/accounts.py:268 src/backend/models/accounts.py:140
msgid "CREATE_SUPPLIER_ERROR"
msgstr "Erreur lors de la création du compte fournisseur"

#: src/backend/controllers/accounts.py:269
msgid "SUPPLIER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte fournisseur existe déjà avec ce numéro de TVA"

#: src/backend/controllers/accounts.py:292 src/backend/controllers/user.py:99
#: src/backend/models/accounts.py:192 src/backend/models/accounts.py:211
#: src/backend/models/accounts.py:226 src/backend/models/user.py:133
msgid "GET_CUSTOMER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du compte client"

#: src/backend/controllers/accounts.py:334
#: src/backend/controllers/accounts.py:340 src/backend/models/accounts.py:244
msgid "UPDATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la mise à jour du compte client"

#: src/backend/controllers/accounts.py:371
#: src/backend/controllers/accounts.py:377 src/backend/models/accounts.py:260
msgid "CREATE_CUSTOMER_ERROR"
msgstr "Erreur lors de la création du compte client"

#: src/backend/controllers/accounts.py:378
msgid "CUSTOMER_VAT_NUMBER_ALREADY_EXISTS"
msgstr "Un compte client existe déjà avec ce numéro de TVA"

#: src/backend/controllers/accounts.py:394
#: src/backend/controllers/accounts.py:400 src/backend/models/accounts.py:278
msgid "DELETE_CUSTOMER_ERROR"
msgstr "Erreur lors de la suppression du compte client"

#: src/backend/controllers/accounts.py:417
#: src/backend/controllers/accounts.py:423 src/backend/models/accounts.py:158
msgid "DELETE_SUPPLIER_ERROR"
msgstr "Erreur lors de la suppression du compte fournisseur"

#: src/backend/controllers/accounts.py:441
msgid "LOAD_SUPPLIER_REFERENCIAL_ERROR"
msgstr "Erreur lors du chargement du référentiel fournisseur"

#: src/backend/controllers/auth.py:80
msgid "LOGIN_ERROR"
msgstr "Erreur lors de la connexion"

#: src/backend/controllers/auth.py:95 src/backend/controllers/auth.py:103
#: src/backend/controllers/auth.py:105
msgid "JWT_ERROR"
msgstr "Erreur lors de l'authentification par token"

#: src/backend/controllers/doctypes.py:131
msgid "DOCTYPESEPARATOR"
msgstr "SEPARATEUR AVEC TYPE DE DOCUMENT / SEPARATOR WITH DOCUMENT TYPE"

#: src/backend/controllers/doctypes.py:134
msgid "DOCUMENTSEPARATOR"
msgstr "SEPARATEUR DE DOCUMENT / DOCUMENT SEPARATOR"

#: src/backend/controllers/doctypes.py:137
msgid "BUNDLESEPARATOR"
msgstr "SEPARATEUR DE LOT / BUNDLE SEPARATOR"

#: src/backend/controllers/forms.py:66 src/backend/controllers/forms.py:115
#: src/backend/models/forms.py:52
msgid "GET_FORM_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du formulaire"

#: src/backend/controllers/forms.py:98
msgid "GET_FORM_FIELDS_BY_FORM_ID_ERROR"
msgstr "Erreur lors de la récupération des champs du formulaire"

#: src/backend/controllers/forms.py:162 src/backend/controllers/forms.py:168
msgid "DELETE_FORM_ERROR"
msgstr "Erreur lors de la suppression du formulaire"

#: src/backend/controllers/forms.py:180 src/backend/controllers/inputs.py:70
#: src/backend/controllers/outputs.py:64
#: src/backend/controllers/positions_masks.py:154
msgid "COPY_OF"
msgstr "Copie de"

#: src/backend/controllers/forms.py:197 src/backend/controllers/forms.py:203
msgid "DUPLICATE_FORM_ERROR"
msgstr "Erreur lors de la duplication du formulaire"

#: src/backend/controllers/forms.py:220 src/backend/controllers/forms.py:226
msgid "DISABLE_FORM_ERROR"
msgstr "Erreur lors de la désactivation du formulaire"

#: src/backend/controllers/forms.py:243 src/backend/controllers/forms.py:249
msgid "ENABLE_FORM_ERROR"
msgstr "Erreur lors de l'activation du formulaire"

#: src/backend/controllers/forms.py:282 src/backend/controllers/forms.py:288
msgid "UPDATE_FORMS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/controllers/history.py:28
msgid "ADD_HISTORY_ERROR"
msgstr "Erreur lors de l'ajout dans l'historique"

#: src/backend/controllers/inputs.py:49 src/backend/controllers/inputs.py:55
msgid "UPDATE_INPUT_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne entrante"

#: src/backend/controllers/inputs.py:83 src/backend/controllers/inputs.py:89
msgid "DUPLICATE_INPUT_ERROR"
msgstr "Erreur lors de la duplication de la chaîne entrante"

#: src/backend/controllers/inputs.py:116 src/backend/controllers/inputs.py:127
#: src/backend/controllers/inputs.py:140
msgid "CREATE_INPUT_ERROR"
msgstr "Erreur lors de la création de la chaîne entrante"

#: src/backend/controllers/inputs.py:117
msgid "INPUT_ID_ALREADY_EXISTS"
msgstr "Le libellé technique de la chaîne entrante existe déjà"

#: src/backend/controllers/inputs.py:128
msgid "INPUT_FOLDER_ALREADY_EXISTS"
msgstr "Le chemin de capture est déjà paramétré dans une autre chaîne entrante"

#: src/backend/controllers/inputs.py:153
msgid "GET_INPUT_BY_ID_ERROR"
msgstr "Erreur lors de récupération de la chaîne entrante"

#: src/backend/controllers/inputs.py:177 src/backend/controllers/inputs.py:183
msgid "DELETE_INPUT_ERROR"
msgstr "Erreur lors de le suppression de la chaîne entrante"

#: src/backend/controllers/inputs.py:212
msgid "FS_WATCHER_DELETION_ERROR"
msgstr "Erreur lors de la suppression des paramètres du fs watcher"

#: src/backend/controllers/inputs.py:213 src/backend/controllers/inputs.py:270
msgid "FS_WATCHER_CONFIG_DOESNT_EXIST"
msgstr "La configuration du fs watcher est introuvable"

#: src/backend/controllers/inputs.py:251 src/backend/controllers/inputs.py:269
msgid "FS_WATCHER_CREATION_ERROR"
msgstr "Erreur lors de la création des paramètres du fs watcher"

#: src/backend/controllers/inputs.py:252
msgid "CAN_NOT_CREATE_FOLDER_PERMISSION_ERROR"
msgstr "Problème de permissions pour créer le dossier"

#: src/backend/controllers/inputs.py:275
msgid "SCRIPT_SAMPLE_DOESNT_EXISTS"
msgstr "Le script d'exemple n'existe pas"

#: src/backend/controllers/inputs.py:281
msgid "SCRIPT_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier des scripts n'existe pas"

#: src/backend/controllers/outputs.py:71 src/backend/controllers/outputs.py:77
msgid "DUPLICATE_OUTPUT_ERROR"
msgstr "Erreur lors de la duplication de la chaîne sortante"

#: src/backend/controllers/outputs.py:103
#: src/backend/controllers/outputs.py:109
msgid "UPDATE_OUTPUT_ERROR"
msgstr "Erreur lors de mise à jour de la chaîne sortante"

#: src/backend/controllers/outputs.py:135
msgid "CREATE_OUTPUT_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/controllers/outputs.py:148
msgid "GET_OUTPUT_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de la chaîne sortante"

#: src/backend/controllers/outputs.py:161
msgid "GET_OUTPUT_TYPE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération des types de chaîne sortante"

#: src/backend/controllers/outputs.py:178
#: src/backend/controllers/outputs.py:184
msgid "DELETE_OUTPUT_ERROR"
msgstr "Erreur lors de la suppression de la chaîne sortante"

#: src/backend/controllers/positions_masks.py:75
#: src/backend/controllers/positions_masks.py:92
msgid "GET_POSITION_MASK_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/controllers/positions_masks.py:137
#: src/backend/controllers/positions_masks.py:143
msgid "DELETE_POSITION_MASK_ERROR"
msgstr "Erreur lors de la suppression du masque de positionnement"

#: src/backend/controllers/positions_masks.py:170
#: src/backend/controllers/positions_masks.py:176
msgid "DUPLICATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la duplication du masque de positionnement"

#: src/backend/controllers/positions_masks.py:193
#: src/backend/controllers/positions_masks.py:199
msgid "DISABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de désactivation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:216
#: src/backend/controllers/positions_masks.py:222
msgid "ENABLE_POSITION_MASK_ERROR"
msgstr "Erreur lors de l'activation du masque de positionnement"

#: src/backend/controllers/positions_masks.py:247
msgid "UPDATE_POSITIONS_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:272
msgid "UPDATE_PAGES_BY_POSITIONS_MASK_ID_ERROR"
msgstr "Erreur lors de la mise à jour des pages du masque de positionnement"

#: src/backend/controllers/positions_masks.py:292
msgid "DELETE_POSITIONS_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des positions du masque de positionnement"

#: src/backend/controllers/positions_masks.py:312
msgid "DELETE_PAGES_BY_POSITION_MASK_ID_ERROR"
msgstr "Erreur lors de la suppression des pages du masque de positionnement"

#: src/backend/controllers/privileges.py:36
#: src/backend/controllers/privileges.py:64
msgid "GET_PRIVILEGES_ERROR"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/controllers/roles.py:53 src/backend/controllers/roles.py:59
#: src/backend/controllers/roles.py:106 src/backend/controllers/roles.py:112
#: src/backend/models/roles.py:70
msgid "UPDATE_ROLE_ERROR"
msgstr "Erreur lors de la mise à jour du rôle"

#: src/backend/controllers/roles.py:84 src/backend/models/roles.py:86
msgid "CREATE_ROLE_ERROR"
msgstr "Erreur lors de la création du rôle"

#: src/backend/controllers/roles.py:125
msgid "GET_ROLE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du rôle"

#: src/backend/controllers/roles.py:142 src/backend/controllers/roles.py:148
msgid "DELETE_ROLE_ERROR"
msgstr "Erreur lors de la suppression du rôle"

#: src/backend/controllers/roles.py:165 src/backend/controllers/roles.py:171
msgid "DISABLE_ROLE_ERROR"
msgstr "Erreur lors de la désactivation du rôle"

#: src/backend/controllers/roles.py:188 src/backend/controllers/roles.py:194
msgid "ENABLE_ROLE_ERROR"
msgstr "Erreur lors de l'activation du rôle"

#: src/backend/controllers/splitter.py:79
msgid "LOAD_METADATA_ERROR"
msgstr "Erreur du chargement des métadonnées"

#: src/backend/controllers/splitter.py:107
#: src/backend/controllers/verifier.py:76
msgid "AT"
msgstr "à"

#: src/backend/controllers/splitter.py:224
msgid "ADD_DOCUMENT_ERROR"
msgstr "Erreur lors de l'ajout d'un document"

#: src/backend/controllers/splitter.py:275
#: src/backend/controllers/splitter.py:281
#: src/backend/controllers/verifier.py:474
#: src/backend/controllers/verifier.py:480
#: src/backend/controllers/verifier.py:486
msgid "EXPORT_MAARCH_ERROR"
msgstr "Erreur lors de l'export vers Maarch"

#: src/backend/controllers/splitter.py:287
#: src/backend/controllers/verifier.py:498
msgid "MAARCH_WS_INFO_EMPTY"
msgstr "Les informations de connexion à Maarch sont vides"

#: src/backend/controllers/splitter.py:313
#: src/backend/controllers/splitter.py:554
msgid "EXPORT_PDF_ERROR"
msgstr "Erreur lors de l'export PDF"

#: src/backend/controllers/splitter.py:330
#: src/backend/controllers/splitter.py:574
#: src/backend/controllers/verifier.py:590
msgid "EXPORT_XML_ERROR"
msgstr "Erreur lors de l'export XML"

#: src/backend/controllers/splitter.py:351
msgid "UPDATE_BATCH_ERROR"
msgstr "Erreur lors de la mise à jour du lot"

#: src/backend/controllers/splitter.py:366
msgid "UPDATE_DOCUMENTS_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/controllers/splitter.py:382
msgid "UPDATE_DOCUMENT_ERROR"
msgstr "Erreur lors de la mise à jour du document"

#: src/backend/controllers/splitter.py:397
#: src/backend/controllers/splitter.py:418
#: src/backend/controllers/splitter.py:433
#: src/backend/controllers/splitter.py:448
msgid "UPDATE_PAGES_ERROR"
msgstr "Erreur lors de la modification des pages"

#: src/backend/controllers/splitter.py:462
msgid "CMIS_CONNECTION_ERROR"
msgstr "Erreur lors de la connexion CMIS"

#: src/backend/controllers/splitter.py:645
#: src/backend/controllers/verifier.py:743 src/backend/models/splitter.py:401
#: src/backend/models/verifier.py:137
msgid "GET_TOTALS_ERROR"
msgstr "Erreur lors de la récupération des totaux"

#: src/backend/controllers/status.py:35
msgid "RETRIEVES_STATUS_ERROR"
msgstr "Erreur lors de la récupération des status"

#: src/backend/controllers/user.py:31
msgid "CREATE_USER_ERROR"
msgstr "Erreur lors de la création de l'utilisateur"

#: src/backend/controllers/user.py:69 src/backend/models/user.py:114
msgid "GET_USER_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de l'utilisateur"

#: src/backend/controllers/user.py:113
msgid "UPDATE_PROFILE"
msgstr "Mise à jour du profile"

#: src/backend/controllers/user.py:114
msgid "ERROR_OLD_PASSWORD_NOT_MATCH"
msgstr "L'ancien mot de passe ne corresponds pas"

#: src/backend/controllers/user.py:119
msgid "UPDATE_USER"
msgstr "Mise à jour de l'utilisateur"

#: src/backend/controllers/user.py:120
msgid "ERROR_PASSWORD_NOT_MATCH"
msgstr "Les mots de passes ne correspondent pas"

#: src/backend/controllers/user.py:147 src/backend/controllers/user.py:153
#: src/backend/models/user.py:152
msgid "UPDATE_USER_ERROR"
msgstr "Erreur lors de la mise à jour de l'utilisateur"

#: src/backend/controllers/user.py:170 src/backend/controllers/user.py:176
msgid "DELETE_USER_ERROR"
msgstr "Erreur lors de la suppression de l'utilisateur"

#: src/backend/controllers/user.py:193 src/backend/controllers/user.py:199
msgid "DISABLE_USER_ERROR"
msgstr "Erreur lors de désactiver de l'utilisateur"

#: src/backend/controllers/user.py:216 src/backend/controllers/user.py:222
msgid "ENABLE_USER_ERROR"
msgstr "Erreur lors de l'activation de l'utilisateur"

#: src/backend/controllers/user.py:242 src/backend/controllers/user.py:248
#: src/backend/models/user.py:170
msgid "UPDATE_CUSTOMERS_USER_ERROR"
msgstr "Erreur lors de la mise à jour des comptes clients de l'utilisateur"

#: src/backend/controllers/verifier.py:57 src/backend/models/verifier.py:34
msgid "GET_INVOICE_BY_ID_ERROR"
msgstr "Erreur lors de la récupération de la facture"

#: src/backend/controllers/verifier.py:164
#: src/backend/controllers/verifier.py:254
msgid "UPDATE_INVOICE_POSITIONS_ERROR"
msgstr "Erreur lors de la mise à jour des positions de la facture"

#: src/backend/controllers/verifier.py:189
#: src/backend/controllers/verifier.py:274
msgid "UPDATE_INVOICE_PAGES_ERROR"
msgstr "Erreur lors de la mise à jour des pages de la facture"

#: src/backend/controllers/verifier.py:213
#: src/backend/controllers/verifier.py:233
msgid "UPDATE_INVOICE_DATA_ERROR"
msgstr "Erreur lors de la mise à jour des données de la facture"

#: src/backend/controllers/verifier.py:291
#: src/backend/controllers/verifier.py:297
msgid "DELETE_INVOICE_ERROR"
msgstr "Erreur lors de la suppression de la facture"

#: src/backend/controllers/verifier.py:315
#: src/backend/controllers/verifier.py:321
msgid "UPDATE_INVOICE_ERROR"
msgstr "Erreur lors de la mise à jour de la facture"

#: src/backend/controllers/verifier.py:341
msgid "REMOVE_LOCK_BY_USER_ID_ERROR"
msgstr "Erreur lors de la suppression du verrou sur la facture"

#: src/backend/controllers/verifier.py:481
msgid "PDF_FILE_NOT_FOUND"
msgstr "Le fichier PDF est introuvable"

#: src/backend/controllers/verifier.py:492
msgid "MAARCH_WS_INFO_WRONG"
msgstr "Les informations de connexion à Maarch sont erronées"

#: src/backend/controllers/verifier.py:584
msgid "XML_DESTINATION_FOLDER_DOESNT_EXISTS"
msgstr "Le dossier de destination XML n'existe pas"

#: src/backend/controllers/verifier.py:669
#: src/backend/controllers/verifier.py:672
#: src/backend/controllers/verifier.py:685
#: src/backend/controllers/verifier.py:702
msgid "API_INSEE_ERROR_CONNEXION"
msgstr "Erreur lors de la connexion à l'api de l'INSEE"

#: src/backend/controllers/verifier.py:724
msgid "VAT_NOT_VALID"
msgstr "Numéro de TVA invalide"

#: src/backend/controllers/verifier.py:728
msgid "VAT_API_ERROR"
msgstr "Impossible de joindre l'API de vérification du numéro de TVA"

#: src/backend/models/accounts.py:90
msgid "SUPPLIER_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour du fournisseur"

#: src/backend/models/auth.py:35 src/backend/models/user.py:37
msgid "BAD_USERNAME"
msgstr "Mauvais nom de compte"

#: src/backend/models/auth.py:37 src/backend/models/user.py:39
msgid "BAD_PASSWORD"
msgstr "Mauvais mot de passe"

#: src/backend/models/auth.py:39
msgid "USER_DELETED"
msgstr "Utilisateur supprimé"

#: src/backend/models/auth.py:41
msgid "USER_DISABLED"
msgstr "Utilisateur desactivé"

#: src/backend/models/config.py:131
msgid "UPDATE_CONFIGURATION_ERROR"
msgstr "Erreur lors de la mise à jour de la configuration"

#: src/backend/models/config.py:149
msgid "UPDATE_REGEX_ERROR"
msgstr "Erreur lors de la mise à jour des REGEX"

#: src/backend/models/config.py:171
msgid "UPDATE_DOCSERVER_ERROR"
msgstr "Erreur lors de la mise à jour de la docserver"

#: src/backend/models/custom_fields.py:48
msgid "ADD_CUSTOM_FIELD_ERROR"
msgstr "Erreur lors de la création du champ custom"

#: src/backend/models/custom_fields.py:51
msgid "CUSTOM_FIELD_ALREADY_EXIST"
msgstr "Le champ custom existe déjà"

#: src/backend/models/custom_fields.py:92
msgid "UPDATE_CUSTOM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour du champ custom"

#: src/backend/models/custom_fields.py:112
msgid "DELETE_CUSTOM_FIELDS_ERROR"
msgstr "Erreur lors de la suppression du champ custom"

#: src/backend/models/doctypes.py:45
msgid "ADD_DOCTYPE_ERROR"
msgstr "Erreur lors de l'ajout d'un type de document"

#: src/backend/models/doctypes.py:48
msgid "DOCTYPE_ALREADY_EXIST"
msgstr "Le type de document existe déjà"

#: src/backend/models/doctypes.py:85
msgid "UPDATE_DOCTYPE_ERROR"
msgstr "Erreur lors de la mise à jour du type de document"

#: src/backend/models/doctypes.py:112 src/backend/models/doctypes.py:115
msgid "SET_DEFAULT_DOCTYPE_ERROR"
msgstr "Erreur lors de la modification du type de document par défaut"

#: src/backend/models/forms.py:71
msgid "GET_DEFAULT_FORM_ERROR"
msgstr "Erreur lors de la récupération du formulaire par défaut"

#: src/backend/models/forms.py:91
msgid "UPDATE_FORM_ERROR"
msgstr "Erreur lors de la mise à jour du formulaire"

#: src/backend/models/forms.py:109
msgid "UPDATE_FORM_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du formulaire"

#: src/backend/models/forms.py:157
msgid "ADD_FORM_ERROR"
msgstr "Erreur lors de la création du formulaire"

#: src/backend/models/forms.py:160
msgid "FORM_LABEL_ALREADY_EXIST"
msgstr "Le libellé de formulaire existe déjà"

#: src/backend/models/inputs.py:50
msgid "INPUT_DOESNT_EXISTS"
msgstr "La chaîne entrante n'existe pas"

#: src/backend/models/inputs.py:84
msgid "INPUT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne entrante"

#: src/backend/models/inputs.py:100
msgid "INPUT_CREATE_ERROR"
msgstr "Erreur lors de la création de la chaîne entrante"

#: src/backend/models/outputs.py:64
msgid "OUTPUT_DOESNT_EXISTS"
msgstr "La chaîne sortante n'existe pas"

#: src/backend/models/outputs.py:83
msgid "OUTPUT_TYPE_DOESNT_EXISTS"
msgstr "Le type de chaîne sortante n'existe aps"

#: src/backend/models/outputs.py:103
msgid "OUTPUT_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la chaîne sortante"

#: src/backend/models/outputs.py:119
msgid "OUTPUT_CREATE_ERROR"
msgstr "Erreur lors de la création de la chaîne sortante"

#: src/backend/models/positions_masks.py:52
msgid "GET_POSITIONS_MASKS_BY_ID_ERROR"
msgstr "Erreur lors de la récupération du masque de positionnement"

#: src/backend/models/positions_masks.py:72
msgid "UPDATE_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la mise à jour du masque de positionnement"

#: src/backend/models/positions_masks.py:90
msgid "UPDATE_POSITIONS_MASKS_FIELDS_ERROR"
msgstr "Erreur lors de la mise à jour des champs du masque de positionnement"

#: src/backend/models/positions_masks.py:120
msgid "ADD_POSITIONS_MASKS_ERROR"
msgstr "Erreur lors de la création du masque de positionnement"

#: src/backend/models/positions_masks.py:123
msgid "POSITIONS_MASK_LABEL_ALREADY_EXIST"
msgstr "Le libellé du masque de positionnement existe déjà"

#: src/backend/models/privileges.py:32 src/backend/models/privileges.py:49
msgid "ERROR_RETRIEVING_PRIVILEGES"
msgstr "Erreur lors de la récupération des privilèges"

#: src/backend/models/roles.py:50
msgid "ROLE_DOESNT_EXISTS"
msgstr "Le rôle n'existe pas"

#: src/backend/models/roles.py:104
msgid "ROLE_PRIVILEGES_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour des privilèges du rôle"

#: src/backend/models/roles.py:122
msgid "ROLE_PRIVILEGES_CREATE_ERROR"
msgstr "Erreur lors de la création des privilèges du rôle"

#: src/backend/models/splitter.py:64
msgid "GET_MAX_SPLIT_INDEX_ERROR"
msgstr "Erreur lors de l'obtention de l'index du Splitter"

#: src/backend/models/splitter.py:103
msgid "UPDATE_SETTINGS_ERROR"
msgstr "Erreur lors de la mise à jour des paramètres du Splitter"

#: src/backend/models/splitter.py:124
msgid "INSERT_PAGE_ERROR"
msgstr "Erreur lors de l'insertion des pages du Splitter"

#: src/backend/models/splitter.py:182
msgid "GET_BATCH_ERROR"
msgstr "Erreur lors de la récupération des lots du Splitter"

#: src/backend/models/splitter.py:201
msgid "GET_DOCUMENTS_ERROR"
msgstr "Erreur lors de la récupération des documents du Splitter"

#: src/backend/models/splitter.py:220
msgid "GET_PAGES_ERROR"
msgstr "Erreur lors de l'obtention des pages du Splitter"

#: src/backend/models/splitter.py:238
msgid "GET_MAX_SOURCE_PAGE_VALUE_ERROR"
msgstr "Erreur lors de l'obtention de la valeur des pages source du Splitter"

#: src/backend/models/splitter.py:257
msgid "GET_DOCUMENT_ERROR"
msgstr "Erreur lors de la récupération du document"

#: src/backend/models/splitter.py:275
msgid "GET_DOCUMENT_MAX_SPLIT_INDEX_ERROR"
msgstr "Erreur lors de l'obtention de l'index maximum du Splitter"

#: src/backend/models/status.py:34
msgid "NO_STATUS"
msgstr "Aucun status existant"

#: src/backend/models/user.py:41
msgid "USER"
msgstr "L'utilisateur"

#: src/backend/models/user.py:41
msgid "ALREADY_REGISTERED"
msgstr "est déjà enregistré"

#: src/backend/models/verifier.py:86 src/backend/models/verifier.py:103
msgid "INVOICE_UPDATE_ERROR"
msgstr "Erreur lors de la mise à jour de la facture"

#: src/backend/rest/auth.py:36
msgid "PGSQL_ERROR"
msgstr "Erreur lors de la connexion à la base de donnée"

#: src/backend/rest/splitter.py:39 src/backend/rest/verifier.py:37
msgid "UNKNOW_ERROR"
msgstr "Erreur inconnue"

#~ msgid "ADD_DOC_TYPE_ERROR"
#~ msgstr "Error while adding document type"

#~ msgid "CHANGE_LOCALE_ERROR"
#~ msgstr "Erreur lors du changement de langue"

#~ msgid "INPUT_FOLDER_DOESNT_EXISTS_OR_NOT_WRITEABLE"
#~ msgstr "Le dossier spécifié n'existe pas ou n'est pas accessible"

#~ msgid "GET_DEMAND_NUMBER_ERROR"
#~ msgstr "Erreur lors de l'obtention du numéro de demande du Splitter"

#~ msgid "INSERT_REFERENTIAL_ERROR"
#~ msgstr "Erreur lors de l'insertion du référentiel de Splitter"

